---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: myteam-repository
  namespace: default
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/rcalin95/workshop-flux-myteam.git
