apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: myteam2-kustomization
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./team2
  prune: true
  sourceRef:
    kind: GitRepository
    name: myteam-repository