apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: myteam1-kustomization
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./team1
  prune: true
  sourceRef:
    kind: GitRepository
    name: myteam-repository